apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: 3-tier-app
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: 949638458026.dkr.ecr.us-east-2.amazonaws.com/3tier-frontend-registry:2024-01-20_19-01-49
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://ajaycodelab.com/api/tasks"
        ports:
        - containerPort: 3000